use crate::domain::Event;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Output categories specified in the architectural vision
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ObservationCategory {
    /// Consistent pattern across long, medium, and short term baselines
    StableBehavior,
    /// Pattern appearing in recent data with no precedent in historical baselines
    NewBehavior,
    /// Gradual shift between medium-term and long-term baselines
    BehaviorDrift,
    /// High anomaly score across all temporal layers simultaneously
    SuddenAnomaly,
}

/// A structured observation generated by the detection layer
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BehaviorObservation {
    pub entity_id: Uuid,
    pub entity_canonical_name: String,
    pub category: ObservationCategory,
    pub title: String,
    pub description: String,
    pub anomaly_score: f64,
    pub timestamp: DateTime<Utc>,
}

/// An event annotated with breakdown scores from all 3 signal components
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ScoredEvent {
    pub event: Event,
    pub sequence_score: f64,
    pub velocity_score: f64,
    pub graph_score: f64,
    pub fused_score: f64,
}

/// Ranked summary of an entity whose behavior has changed significantly
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MostChangedEntity {
    pub entity_id: Uuid,
    pub canonical_name: String,
    pub entity_type: String,
    pub drift_score: f64,
    pub anomaly_score: f64,
    pub combined_change_score: f64,
    pub new_behaviors_count: usize,
}
